### ISSUE TITLE
Mute button and video button customization

### ISSUE THREAD

**Issue by AlishaAugurs** [zoom/videosdk-ui-toolkit-ios#1]
1. How to disable Video button for Audio session. 
2. The Mic button is muted when the button shows as NOT muted.
3. By default call is muted.

**Comment by BoonJunTan** [comment]
Hi @AlishaAugurs,

**How to disable Video button for Audio session.** 
Do you mean you would like to have a session with only audio and not the user's camera video? If that is the case, we currently do not offer this customizable option at the moment but we will definitely be adding this in our future release.

**The Mic button is muted when the button shows as NOT muted.**
Currently, the mic button shows the mic status if a user clicks on the button instead of its current status. I know that this is confusing right now so look forward to our next release which we are also improving some of the UI/UX elements and the mic and camera buttons are part of the update.

**By default call is muted.**
Currently by default the camera video is on and the mic audio is off. We currently do not offer a customizable option for this right now but we will definitely be adding this in our future release.

I hope I answered your question and thank you for your interest in our UI Toolkit. Please feel free to ask me anything related to this.
